Repository zigpy/zha, pull requests merged in 2024-11, with the labels that each got.

#304 Adjust step to 0.1 for Sonoff thermostat calibration
  zha/application/platforms/number/__init__.py
Labels: enhancement, entities

#306 Use `NumberMode.BOX` for local temperature calibration
  zha/application/platforms/number/__init__.py
Labels: enhancement, entities

#292 Device alerts
  tests/test_device.py
  zha/zigbee/device.py
Labels: enhancement

#267 Convert ZCL attributes from strings when writing
  tests/test_application_helpers.py
  zha/application/helpers.py
  zha/zigbee/device.py
Labels: bugfix
