Repository zigpy/zha, pull requests merged in 2025-01, with the labels that each got.

#341 Fix missing state_class for quirk v2 sensors
  tests/test_sensor.py
  zha/application/platforms/sensor/__init__.py
Labels: bugfix, priority: medium

#352 Remove unnecessary unit validation
  tests/test_units.py
  zha/application/platforms/number/__init__.py
  zha/application/platforms/sensor/__init__.py
  zha/units.py
Labels: bugfix

#339 Add remaining 3 phase electrical attributes
  tests/test_cluster_handlers.py
  tests/test_sensor.py
  zha/application/platforms/sensor/__init__.py
  zha/zigbee/cluster_handlers/homeautomation.py
Labels: entities

#359 Add test checking SmartEnergy Metering polling
  tests/test_sensor.py
Labels: only tests

#358 Fix issues with `read_attributes` and `attribute_updated`
  zha/application/platforms/switch.py
  zha/zigbee/cluster_handlers/__init__.py
  zha/zigbee/cluster_handlers/closures.py
  zha/zigbee/cluster_handlers/general.py
  zha/zigbee/cluster_handlers/homeautomation.py
  zha/zigbee/cluster_handlers/manufacturerspecific.py
  zha/zigbee/cluster_handlers/smartenergy.py
Labels: bugfix

#361 Replace deprecated `add_to_registry_v2` in tests
  tests/test_button.py
Labels: only tests, code quality

#363 Implement quirks v2 reporting config, optimize discovery
  tests/test_sensor.py
  zha/application/const.py
  zha/application/discovery.py
  zha/zigbee/cluster_handlers/manufacturerspecific.py
Labels: enhancement, quirks
